stages:
  - lint
  - test

variables:
  PYTHON_VERSION: "3.11"
  VENV_PATH: ".venv"

cache:
  paths:
    - .venv/

before_script:
  - python3 -m venv $VENV_PATH
  - source $VENV_PATH/bin/activate
  - pip install --upgrade pip poetry
  - poetry install

lint:
  stage: lint
  script:
    - poetry run ruff check .
  artifacts:
    paths:
      - ruff-report.json
    when: always

test:
  stage: test
  script:
    - poetry run pytest
  artifacts:
    reports:
      junit: pytest_results.xml
