- question: How to prepare a good sleep environment?
  instruction_path: ../../configs/instructions/sleep_environment.md
- question: How to clean my forehead?
  instruction_path: ../../configs/instructions/clean_forehead.md
- question: How to clean the patch?
  instruction_path: ../../configs/instructions/clean_patch.md
- question: How to change the patch?
  instruction_path: ../../configs/instructions/change_patch.md
- question: Where should I place my laptop?
  instruction_path: ../../configs/instructions/laptop_placement.md
- question: How to connect the EEG headband receiver?
  instruction_path: ../../configs/instructions/receiver_connection.md
- question: How to turn on the EEG headband?
  instruction_path: ../../configs/instructions/turn_on_headband.md
- question: What do the light indicators on the EEG headband mean?
  instruction_path: ../../configs/instructions/light_indicator.md
- question: What if the hair on my forehead and temples is too long?
  instruction_path: ../../configs/instructions/cut_hair_headband.md
- question: How to do reality checks?
  instruction_path: ../../configs/instructions/reality_checks.md
- question: What should I do if I clicked "I'm Awake" on the sleep page but I'm not ready for the questionnaires?
  instruction_path: ../../configs/instructions/accident_click_I'm_awake.md
- question: Do I need to do anything in the daytime?
  instruction_path: ../../configs/instructions/daily_routine.md
- question: How to reconnect the EEG headband?
  instruction_path: ../../configs/instructions/how_to_reconnect.md
- question: How to reset the EEG headband?
  instruction_path: ../../configs/instructions/reset_headband.md