- type: PlayAudioFile
  file_path: ../../configs/audios/main_training/instruction_1.wav
- type: Pause
  duration: 60
- type: PlayAudioFile
  file_path: ../../configs/audios/main_training/instruction_2.wav
- type: Pause
  duration: 240
- type: PlayAudioFile
  file_path: ../../configs/audios/main_training/instruction_3.wav
- type: Pause
  duration: 60
- type: LightCue
  led_color: RED
  led_intensity_increase: 15
  on_duration: 5
  off_duration: 5
  repetitions: 3
- type: PlayAudioFile
  file_path: ../../configs/audios/main_training/prompt_1.wav
- type: Pause
  duration: 60
- type: SemanticAudioCue
  text: You are dreaming
  volume_increase: 15
- type: PlayAudioFile
  file_path: ../../configs/audios/main_training/prompt_2.wav
- type: Pause
  duration: 60
- type: VibrationCue
  on_duration: 2
  off_duration: 5
  repetitions: 3
- type: PlayAudioFile
  file_path: ../../configs/audios/main_training/prompt_3.wav
- type: Pause
  duration: 60
- type: LightCue
  led_color: RED
  led_intensity_increase: 10
  on_duration: 5
  off_duration: 5
  repetitions: 3
- type: PlayAudioFile
  file_path: ../../configs/audios/main_training/prompt_4.wav
- type: Pause
  duration: 60
- type: SemanticAudioCue
  text: You are dreaming
  volume_increase: 10
- type: PlayAudioFile
  file_path: ../../configs/audios/main_training/prompt_5.wav
- type: Pause
  duration: 60
- type: VibrationCue
  on_duration: 2
  off_duration: 5
  repetitions: 2
- type: PlayAudioFile
  file_path: ../../configs/audios/main_training/prompt_6.wav
- type: Pause
  duration: 5
- type: PlayAudioFile
  file_path: ../../configs/audios/main_training/instruction_4.wav
- type: Pause
  duration: 60
- type: LightCue
  led_color: RED
  led_intensity_increase: 5
  on_duration: 5
  off_duration: 5
  repetitions: 3
- type: Pause
  duration: 60
- type: SemanticAudioCue
  text: You are dreaming
  volume_increase: 5
- type: Pause
  duration: 60
- type: VibrationCue
  on_duration: 2
  off_duration: 5
  repetitions: 2
- type: Pause
  duration: 60
- type: LightCue
  led_color: RED
  led_intensity_increase: 0
  on_duration: 5
  off_duration: 5
  repetitions: 3
- type: Pause
  duration: 60
- type: SemanticAudioCue
  text: You are dreaming
  volume_increase: 0
- type: Pause
  duration: 60
- type: VibrationCue
  on_duration: 2
  off_duration: 5
  repetitions: 1
- type: PlayAudioFile
  file_path: ../../configs/audios/main_training/prompt_6.wav
- type: Pause
  duration: 5
