data_dir: "data"

storage:
  survey_data_dir: "data/survey_results" # TODO: we should have a dedicate survey section in the settings
  datetime_format: "%Y-%m-%dT%H:%M:%S"  # ISO 8601 format # TODO: this should be a global setting

hdf5:
  compression: gzip

zmax:
  retry_attempts: 3
  retry_delay: 1
  socket_timeout: 10

logging:
  console:
    level: "INFO"
    format: "{time} | {level} | {message}"
  file:
    file_name: "slumber.log"
    level: "DEBUG"
    format: "{time} | {level} | {module}:{function}:{line} | {message}"
    rotation: "50 MB"
    serialize: True
    enqueue: True

audit:
  file_name: "audit.tsv"
  rotation: "50 MB"
  enqueue: True
