time_zone: "Europe/Amsterdam"

storage:
  survey_data_dir: "data/survey_results" # TODO: we should have a dedicate survey section in the settings
<<<<<<< HEAD
=======
  datetime_format: "%Y-%m-%dT%H:%M:%S" # ISO 8601 format # TODO: this should be a global setting
>>>>>>> 6ba7e0b (added database model)

hdf5:
  compression: gzip

zmax:
  ip: 127.0.0.1
  port: 8000
  retry_attempts: 12
  retry_delay: 5
  socket_timeout: 10

sleep_scoring:
  labels:
    wake: W
    n1: N1
    n2: N2
    n3: N3
    rem: REM
    unknown: UNKNOWN

logging:
  include_timestamp_in_file_name: false
  handlers:
    console:
      level: "INFO"
      colorize: True
    file:
      file_name: "slumber"
      level: "DEBUG"
      format: "{message}"
      rotation: "50 MB"
      serialize: True
      enqueue: True

text2speech:
  rate: 175 # Integer speech rate in words per minute.
  volume: 100 # [0, 100]

lr_eye_movement:
  left_label: L
  right_label: R
  difference_threshold: 280
  min_same_event_gap: 0.5
  max_sequence_gap: 1.5
  low_cutoff: 0.3
  high_cutoff: 2

arousal_detection:
  wake_n1_threshold: 0.4
  min_duration: 3.0
  max_duration: 15.0
  merge_gap: 5.0
  smoothing_window: 5.0
  min_transition_increase: 0.2
  gap_threshold_factor: 0.8
  arousal_label: AROUSAL
  
gui_config:
  font_size: 0
  app_width: 1920
  app_height: 1080
  app_mode: window
  language: English

study_config:
  duration: 14

procedure_tasks:
  - name: Pre-Sleeping Survey
    header: Fill in Pre-Sleeping Survey
    module: slumber.gui.pages.procedure.tasks.pre_sleeping_survey
    type: pre_processing
    enabled: true
  - name: Plugin the receiver
    header: Plugin the receiver
    module: slumber.gui.pages.procedure.tasks.plugin_the_receiver
    type: pre_processing
    enabled: true
  - name: Start ZMax Server
    header: Start ZMax Server
    module: slumber.gui.pages.procedure.tasks.start_zmax_server
    type: pre_processing
    enabled: true
  - name: Put on and start headband
    header: Put on and start headband
    module: slumber.gui.pages.procedure.tasks.put_on_and_start_headband
    type: pre_processing
    enabled: true
  - name: Setup and calibrate ZMax
    header: Setup and calibrate ZMax
    module: slumber.gui.pages.procedure.tasks.setup_and_calibrate_zmax
    type: pre_processing
    enabled: true
  - name: Start Recording
    header: Start Recording
    module: slumber.gui.pages.procedure.tasks.start_recording
    type: action
    enabled: true
  - name: Fill in Post-Sleeping Survey
    header: Fill in Post-Sleeping Survey
    module: slumber.gui.pages.procedure.tasks.fill_in_post_sleeping_survey
    type: post_processing
    enabled: true
