time_zone: "Europe/Amsterdam"
process_termination_timeout: 10.0

database:
  name: slumber.db

hdf5:
  compression: gzip

zmax:
  ip: 127.0.0.1
  port: 8000
  retry_attempts: 3
  retry_delay: 5
  socket_timeout: 10
  hypnodyne_suite_directory: "C:/Users/Mahdad/Desktop/ZMax"

sleep_scoring:
  labels:
    wake: W
    n1: N1
    n2: N2
    n3: N3
    rem: REM
    unknown: UNKNOWN

logging:
  include_timestamp_in_file_name: false
  handlers:
    console:
      level: "INFO"
      colorize: True
    file:
      level: "DEBUG"
      format: "{message}"
      rotation: "50 MB"
      serialize: True
      enqueue: True

text2speech:
  rate: 175 # Integer speech rate in words per minute.
  volume: 100 # [0, 100]

lr_eye_movement:
  left_label: L
  right_label: R
  difference_threshold: 280
  min_same_event_gap: 0.5
  max_sequence_gap: 1.5
  low_cutoff: 0.3
  high_cutoff: 2

arousal_detection:
  wake_n1_threshold: 0.4
  min_duration: 3.0
  max_duration: 15.0
  merge_gap: 5.0
  smoothing_window: 5.0
  min_transition_increase: 0.2
  gap_threshold_factor: 0.8
  arousal_label: AROUSAL
  
gui:
  font_size: 0
  app_width: 1920
  app_height: 1080
  app_mode: window
  language: English

study:
  duration: 14

tasks:
  default: base

survey:
  response_indent: 4