name: zmax_data_collection

components:
  ZMAX:
    unit: ZMaxDataReceiver
    settings:
      zmax:
        socket_timeout: 5
      data_types:
        - EEG_LEFT
        - EEG_RIGHT
      retry_attempts: 6
      retry_delay: 10

  ZMAX_STORAGE_QUEUE:
    unit: CountQueue
    settings:
      max_size: 5120 
      leaky: False
      log_queue_size_interval: 5
      publish_interval: 0.01
      publish_count: 2560

  ZMAX_STORAGE:
    unit: HDF5Storage
    settings:
      file_path: ./data/storage.h5
      group_name: "zmax_raw"


connections:
  - [ZMAX.SAMPLE, ZMAX_STORAGE_QUEUE.INPUT]
  - [ZMAX_STORAGE_QUEUE.OUTPUT, ZMAX_STORAGE.INPUT]
