name: home_lucid_dreaming

components:
  
  ZMAX:
    unit: ZMaxDataReceiver
    settings:
      zmax:
        socket_timeout: 1
      data_types:
        - EEG_LEFT
        - EEG_RIGHT
      retry_attempts: 6
      retry_delay: 10

  ZMAX_STORAGE_QUEUE:
    unit: CountQueue
    settings:
      max_size: 5120 
      leaky: False
      log_queue_size_interval: 5
      publish_interval: 0.01
      publish_count: 2560

  ZMAX_SAMPLE_RATE_REGULATOR:
    unit: TimeQueue
    settings:
      max_size: 5120
      leaky: True
      log_queue_size_interval: 5
      publish_interval: 10
      sample_rate: 256
      gap_threshold: 1.0
      channel_names: [EEG_LEFT, EEG_RIGHT]
      timestamp_margin: 1.0

  ZMAX_STORAGE:
    unit: HDF5Storage
    settings:
      file_path: ./data/storage.h5
      group_name: "zmax_raw"

  PREPROCESS:
    unit: Transform
    settings:
      transforms:
        - class_name: ArraySelector
          kwargs:
            channels: [EEG_LEFT, EEG_RIGHT]
        - class_name: Resample
          kwargs:
            new_sample_rate: 128

  SLEEP_SCORING_ROLLING_BUFFER:
    unit: RollingBuffer
    settings:
      size: 105

  SLEEP_SCORING_PREPROCESS:
    unit: Transform
    settings:
      transforms:
        - class_name: FIRFilter
          kwargs:
            low_cutoff: 0.3
            high_cutoff: 30.0

  SLEEP_SCORING:
    unit: SleepScoring
    settings:
      model:
        model_dir: ../../tests/resources/sample_utime_model
        n_periods: 105
        n_samples_per_prediction: 1
      channel_groups: [[EEG_LEFT], [EEG_RIGHT]]
      arg_max: false

  AROUSAL_DETECTION_SCORES_SELECTOR:
    unit: Transform
    settings:
      transforms:
        - class_name: ArraySelector
          kwargs:
            start_index: -3840 # 30 seconds
      
  MASTER_SCORES_SELECTOR:
    unit: Transform
    settings:
      transforms:
        - class_name: ArraySelector
          kwargs:
            start_index: -7680 # 60 seconds

  EYE_MOVEMENT_DETECTION_ROLLING_BUFFER:
    unit: RollingBuffer
    settings:
      size: 3

  EYE_MOVEMENT_DETECTION:
    unit: EyeMovementDetection
    settings:
      left_eeg_label: EEG_LEFT
      right_eeg_label: EEG_RIGHT
      difference_threshold: 280

  AROUSAL_DETECTION:
    unit: ArousalDetection
    settings:
      wake_n1_threshold: 0.4

  MASTER:
    unit: Master
    settings:
      wake_up_signal:
        vibration: true
        led_color: "OFF"
        on_duration: 5
        off_duration: 5
        repetitions: 3
      cueing_enabled: true
      rem_confidence_threshold: 0.8
      accepted_eye_signals: [LRL, RLR]
      wake_up_signal_interval: 2
      experiment_state: SLEEP

  REM_CUEING:
    unit: Cueing
    settings:
        visual_cueing:
          led_color: RED
          repetitions: 3
          on_duration: 5
          off_duration: 5
          intensity:
            value: 1
            min: 1
            max: 100
            step: 5
        vibration_cueing:
          on_duration: 2
          off_duration: 5
          intensity:
            value: 1
            min: 1
            max: 3
            step: 1
        audio_cueing:
          text: You are dreaming
          rate: 175
          intensity:
            value: 0
            min: 0
            max: 100
            step: 5
        enabled: false
        increase_intensity: false
        enabled_check_interval: 5.0
        cueing_interval: 5.0

  SLEEP_SCORING_STORAGE:
    unit: HDF5Storage
    settings:
      file_path: ./data/storage.h5
      group_name: "sleep_scoring"

  # EYE_MOVEMENT_DETECTION_STORAGE:
  #   unit: MessageLogger
  #   settings:
  #     output: ./home_lucid_dreaming/data/eye_movement_detection.json

  # AROUSAAL_DETECTION_STORAGE:
  #   unit: MessageLogger
  #   settings:
  #     output: ./home_lucid_dreaming/data/arousal_detection.json
       

connections:
  - [ZMAX.SAMPLE, ZMAX_STORAGE_QUEUE.INPUT]
  - [ZMAX.SAMPLE, ZMAX_SAMPLE_RATE_REGULATOR.INPUT]
  - [ZMAX_STORAGE_QUEUE.OUTPUT, ZMAX_STORAGE.INPUT]
  - [ZMAX_SAMPLE_RATE_REGULATOR.OUTPUT, PREPROCESS.INPUT]
  - [PREPROCESS.OUTPUT, SLEEP_SCORING_ROLLING_BUFFER.INPUT]
  - [SLEEP_SCORING_ROLLING_BUFFER.OUTPUT, SLEEP_SCORING_PREPROCESS.INPUT]
  - [SLEEP_SCORING_PREPROCESS.OUTPUT, SLEEP_SCORING.INPUT]
  - [PREPROCESS.OUTPUT, EYE_MOVEMENT_DETECTION_ROLLING_BUFFER.INPUT]
  - [EYE_MOVEMENT_DETECTION_ROLLING_BUFFER.OUTPUT, EYE_MOVEMENT_DETECTION.INPUT]
  - [SLEEP_SCORING.OUTPUT, AROUSAL_DETECTION_SCORES_SELECTOR.INPUT]
  - [AROUSAL_DETECTION_SCORES_SELECTOR.OUTPUT, AROUSAL_DETECTION.INPUT]
  - [SLEEP_SCORING.OUTPUT, MASTER_SCORES_SELECTOR.INPUT]
  - [MASTER_SCORES_SELECTOR.OUTPUT, MASTER.SLEEP_SCORES]
  - [EYE_MOVEMENT_DETECTION.OUTPUT, MASTER.EYE_MOVEMENT_EVENTS]
  - [AROUSAL_DETECTION.OUTPUT, MASTER.AROUSAL_EVENTS]
  - [MASTER.CUEING_ENABLE_SIGNAL, REM_CUEING.ENABLE_SIGNAL]
  - [MASTER.CUEING_ENABLE_INCREASE_INTENSITY_SIGNAL, REM_CUEING.ENABLE_INCREASE_INTENSITY_SIGNAL]
  - [MASTER.CUEING_DECREASE_INTENSITY_SIGNAL, REM_CUEING.DECREASE_INTENSITY_SIGNAL]
  - [REM_CUEING.ZMAX_STIMULATION_SIGNAL, ZMAX.STIMULATION_SIGNAL]
  - [SLEEP_SCORING.OUTPUT, SLEEP_SCORING_STORAGE.INPUT]
  # - [EYE_MOVEMENT_DETECTION.OUTPUT, EYE_MOVEMENT_DETECTION_STORAGE.INPUT_MESSAGE]
  # - [AROUSAL_DETECTION.OUTPUT, AROUSAAL_DETECTION_STORAGE.INPUT_MESSAGE]


process_components: [MASTER, ZMAX, SLEEP_SCORING]
