name: zmax_data_collection

components:
  ZMAX:
    unit: ZMaxDataReceiver
    settings:
      zmax:
        socket_timeout: 5
      data_types:
        - EEG_LEFT
        - EEG_RIGHT
      retry_attempts: 6
      retry_delay: 10

  ZMAX_STORAGE_QUEUE:
    unit: CountQueue
    settings:
      max_size: 5120 
      leaky: False
      log_queue_size_interval: 5
      publish_interval: 0.01
      publish_count: 2560

  ZMAX_STORAGE:
    unit: HDF5Storage
    settings:
      file_path: ./data/storage.h5
      group_name: "zmax_raw"

  GUI:
    unit: GUI
    settings:
      procedure_tasks:
      - name: Pre-Sleeping Survey
        header: Fill in Pre-Sleeping Survey
        module: slumber.gui.pages.procedure.tasks.pre_sleeping_survey
        type: pre_processing
        enabled: true
      - name: Plugin the receiver
        header: Plugin the receiver
        module: slumber.gui.pages.procedure.tasks.plugin_the_receiver
        type: pre_processing
        enabled: true
      - name: Start ZMax Server
        header: Start ZMax Server
        module: slumber.gui.pages.procedure.tasks.start_zmax_server
        type: pre_processing
        enabled: true
      - name: Put on and start headband
        header: Put on and start headband
        module: slumber.gui.pages.procedure.tasks.put_on_and_start_headband
        type: pre_processing
        enabled: true
      - name: Setup and calibrate ZMax
        header: Setup and calibrate ZMax
        module: slumber.gui.pages.procedure.tasks.setup_and_calibrate_zmax
        type: pre_processing
        enabled: true
      - name: Start Recording
        header: Start Recording
        module: slumber.gui.pages.procedure.tasks.start_recording
        type: action
        enabled: true
      - name: Fill in Post-Sleeping Survey
        header: Fill in Post-Sleeping Survey
        module: slumber.gui.pages.procedure.tasks.fill_in_post_sleeping_survey
        type: post_processing
        enabled: true


connections:
  - [ZMAX.SAMPLE, ZMAX_STORAGE_QUEUE.INPUT]
  - [ZMAX_STORAGE_QUEUE.OUTPUT, ZMAX_STORAGE.INPUT]
