name: pilot

gui:
  pre_sleep:
    tasks:
      # - title: EEG Headband Connection
      #   widget: zmax_connection
      #   kwargs:
      #     battery_level_threshold: 10
      # - title: Eye Movement Detection Test
      #   widget: eye_test
      #   kwargs:
      #     accepted_eye_signals: [LRL, RLR]
      #     difference_threshold: 280
      #     max_test_duration: 30
      # - title: Light Cue Calibration
      #   widget: light_cue_calibration
      #   kwargs:
      #     min: 5
      #     max: 100
      #     increment: 5
      #     decrement: 2
      #     led_color: RED
      #     repetitions: 3
      #     on_duration: 5
      #     off_duration: 5
      #     alternate_eyes: false
      #     countdown_seconds: 5
      # - title: Audio Cue Calibration
      #   widget: audio_cue_calibration
      #   kwargs:
      #     min: 5
      #     max: 100
      #     increment: 5
      #     decrement: 2
      #     countdown_seconds: 5
      #     rate: 175
      #     text: You are dreaming
      # - title: Vibration Cue Calibration
      #   widget: vibration_cue_calibration
      #   kwargs:
      #     on_duration: 2
      #     off_duration: 5
      #     repetitions: 2
      #     countdown_seconds: 5
      - title: Voice Recording Assessment
        widget: survey
        kwargs:
          survey_config_path: ../../configs/surveys/voice_recording_test.json
  awakening:
    tasks:
      - title: Before Awakening Experience
        widget: survey
        kwargs:
          survey_config_path: ../../configs/surveys/awakening_questionnaire.json
  post_sleep:
    tasks:
      - title: Lucidity and Consciousness in Dreams
        widget: survey
        kwargs:
          survey_config_path: ../../configs/surveys/lucid_questionnaire.json
      - title: Sleep and Mood
        widget: survey
        kwargs:
          survey_config_path: ../../configs/surveys/sleep_and_mood_questionnaire.json

dag:
  components:
  - name: ZMAX
    unit: ZMaxDataReceiver
    settings:
      zmax:
        socket_timeout: 1
      data_collection_enabled: true
      data_collection_enabled_check_interval: 5.0
      data_types:
        - EEG_LEFT
        - EEG_RIGHT
      retry_attempts: 6
      retry_delay: 10

  - name: ZMAX_STORAGE_QUEUE
    unit: CountQueue
    settings:
      max_size: 5120
      leaky: False
      log_queue_size_interval: 5
      publish_count: 2560

  - name: ZMAX_SAMPLE_RATE_REGULATOR
    unit: TimeQueue
    settings:
      max_size: 5120
      leaky: True
      log_queue_size_interval: 5
      publish_interval: 10
      publish_enabled: true
      publish_enabled_check_interval: 5.0
      sample_rate: 256
      gap_threshold: 1.0
      channel_names: [EEG_LEFT, EEG_RIGHT]
      timestamp_margin: 1.0

  - name: ZMAX_STORAGE
    unit: HDF5Storage
    settings:
      file_path: ./data/storage.h5
      group_name: "zmax_raw"
      flush_after: 90

  - name: PREPROCESS
    unit: Transform
    settings:
      transforms:
        - class_name: ArraySelector
          kwargs:
            channels: [EEG_LEFT, EEG_RIGHT]
        - class_name: Resample
          kwargs:
            new_sample_rate: 128

  - name: ZMAX_PREPROCESSED_STORAGE
    unit: HDF5Storage
    settings:
      file_path: ./data/storage.h5
      group_name: "zmax_preprocessed"
      flush_after: 90

  - name: SLEEP_SCORING_ROLLING_BUFFER
    unit: RollingBuffer
    settings:
      size: 105

  - name: SLEEP_SCORING_PREPROCESS
    unit: Transform
    settings:
      transforms:
        - class_name: FIRFilter
          kwargs:
            low_cutoff: 0.3
            high_cutoff: 30.0

  - name: SLEEP_SCORING
    unit: SleepScoring
    settings:
      model:
        model_dir: C:\Users\Mahdad\Projects\slumber\tests\resources\sample_utime_model
        n_periods: 105
        n_samples_per_prediction: 1
      channel_groups: [[EEG_LEFT], [EEG_RIGHT]]
      arg_max: false

  - name: AROUSAL_DETECTION_SCORES_SELECTOR
    unit: Transform
    settings:
      transforms:
        - class_name: ArraySelector
          kwargs:
            start_index: -3840 # 30 seconds

  - name: MASTER_SCORES_SELECTOR
    unit: Transform
    settings:
      transforms:
        - class_name: ArraySelector
          kwargs:
            start_index: -7680 # 60 seconds

  - name: EYE_MOVEMENT_DETECTION_ROLLING_BUFFER
    unit: RollingBuffer
    settings:
      size: 3

  - name: EYE_MOVEMENT_DETECTION
    unit: EyeMovementDetection
    settings:
      left_eeg_label: EEG_LEFT
      right_eeg_label: EEG_RIGHT
      difference_threshold: 280

  - name: AROUSAL_DETECTION
    unit: ArousalDetection
    settings:
      wake_n1_threshold: 0.4

  - name: MASTER
    unit: Master
    settings:
      wake_up_signal:
        vibration: true
        led_color: "OFF"
        on_duration: 5
        off_duration: 5
        repetitions: 3
      cueing_enabled: true
      rem_confidence_threshold: 0.8
      accepted_eye_signals: [LRL, RLR]
      wake_up_signal_interval: 4
      experiment_state: AWAKE

  - name: REM_CUEING
    unit: Cueing
    settings:
      visual_cueing:
        led_color: RED
        repetitions: 3
        on_duration: 5
        off_duration: 5
        intensity:
          value: 5
          min: 1
          max: 100
          increment: 5
          decrement: 5
      tactile_cueing:
        on_duration: 2
        off_duration: 5
        intensity:
          value: 1
          min: 1
          max: 3
          increment: 1
          decrement: 1
      auditory_cueing:
        text: You are dreaming
        rate: 175
        intensity:
          value: 5
          min: 0
          max: 100
          increment: 5
          decrement: 5
      enabled: false
      increase_intensity: false
      enabled_check_interval: 5.0
      cueing_interval: 20

  - name: SLEEP_SCORING_STORAGE
    unit: HDF5Storage
    settings:
      file_path: ./data/storage.h5
      group_name: "sleep_scoring"
      flush_after: 90

  - name: EVENT_LOGGER
    unit: EventLogger
    settings:
      output: ./data/events.jsonl

  connections:
    - [ZMAX.OUTPUT_SAMPLE, ZMAX_STORAGE_QUEUE.INPUT]
    - [ZMAX.OUTPUT_SAMPLE, ZMAX_SAMPLE_RATE_REGULATOR.INPUT]
    - [ZMAX_STORAGE_QUEUE.OUTPUT, ZMAX_STORAGE.INPUT]
    - [ZMAX_SAMPLE_RATE_REGULATOR.OUTPUT, PREPROCESS.INPUT]
    - [PREPROCESS.OUTPUT, ZMAX_PREPROCESSED_STORAGE.INPUT]
    - [PREPROCESS.OUTPUT, SLEEP_SCORING_ROLLING_BUFFER.INPUT]
    - [SLEEP_SCORING_ROLLING_BUFFER.OUTPUT, SLEEP_SCORING_PREPROCESS.INPUT]
    - [SLEEP_SCORING_PREPROCESS.OUTPUT, SLEEP_SCORING.INPUT]
    - [PREPROCESS.OUTPUT, EYE_MOVEMENT_DETECTION_ROLLING_BUFFER.INPUT]
    - [
        EYE_MOVEMENT_DETECTION_ROLLING_BUFFER.OUTPUT,
        EYE_MOVEMENT_DETECTION.INPUT,
      ]
    - [SLEEP_SCORING.OUTPUT, AROUSAL_DETECTION_SCORES_SELECTOR.INPUT]
    - [AROUSAL_DETECTION_SCORES_SELECTOR.OUTPUT, AROUSAL_DETECTION.INPUT]
    - [SLEEP_SCORING.OUTPUT, MASTER_SCORES_SELECTOR.INPUT]
    - [MASTER_SCORES_SELECTOR.OUTPUT, MASTER.INPUT_SLEEP_SCORES]
    - [EYE_MOVEMENT_DETECTION.OUTPUT, MASTER.INPUT_EYE_MOVEMENT_EVENTS]
    - [AROUSAL_DETECTION.OUTPUT, MASTER.INPUT_AROUSAL_EVENTS]
    - [MASTER.OUTPUT_CUEING_ENABLE_SIGNAL, REM_CUEING.INPUT_ENABLE_SIGNAL]
    - [
        MASTER.OUTPUT_CUEING_ENABLE_INCREASE_INTENSITY_SIGNAL,
        REM_CUEING.INPUT_ENABLE_INCREASE_INTENSITY_SIGNAL,
      ]
    - [
        MASTER.OUTPUT_CUEING_DECREASE_INTENSITY_SIGNAL,
        REM_CUEING.INPUT_ADJUST_INTENSITY_SIGNAL,
      ]
    - [REM_CUEING.OUTPUT_ZMAX_STIMULATION_SIGNAL, ZMAX.INPUT_STIMULATION_SIGNAL]
    - [MASTER_SCORES_SELECTOR.OUTPUT, SLEEP_SCORING_STORAGE.INPUT]
    - [MASTER.OUTPUT_WAKE_UP_SIGNAL, ZMAX.INPUT_STIMULATION_SIGNAL]
    - [MASTER.OUTPUT_LOG_EVENT, EVENT_LOGGER.INPUT_MESSAGE]
    - [REM_CUEING.OUTPUT_LOG_EVENT, EVENT_LOGGER.INPUT_MESSAGE]
