import os

from dotenv import load_dotenv

from slumber import settings

load_dotenv()

LIVEMODE_SENDBYTES_COMMAND = "LIVEMODE_SENDBYTES"
DONGLE_MESSAGE_PREFIX = "_DONGLE"
SENDBYTES_MAX_RETRIES = 1
PACKET_TYPE_POSITION = 0
VALID_PACKET_TYPES = range(1, 12)
EXPECTED_DATA_LENGTH = 119

STIMULATION_RETRY_DELAY = 111  # Milliseconds
STIMULATION_FLASH_LED_COMMAND = 4
STIMULATION_PWM_MAX = 254  # 100% intensity
STIMULATION_MAX_REPETITIONS = 127
STIMULATION_MIN_REPETITIONS = 1
STIMULATION_MIN_DURATION = 1
STIMULATION_MAX_DURATION = 255
LED_MIN_INTENSITY = 1
LED_MAX_INTENSITY = 100
SAMPLE_RATE = 256
MIN_VOLTAGE = 3.12
MAX_VOLTAGE = 4.24

FILE_EXTENSION = "edf"

DEFAULTS = settings["zmax"]
DEFAULTS["hypnodyne_suite_directory"] = DEFAULTS.get(
    "hypnodyne_suite_directory", os.getenv("HYPNODYNE_SUITE_DIRECTORY")
)
QUICKSTART_APP_NAME = "QuickStart.exe"
HYPNODYNE_PROCESSES = ["HDServiceGUI.exe", "HDRecorder.exe", "HDServer.exe"]
